# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2023_04_05_193001) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "active_storage_attachments", force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.bigint "record_id", null: false
    t.bigint "blob_id", null: false
    t.datetime "created_at", null: false
    t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
    t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
  end

  create_table "active_storage_blobs", force: :cascade do |t|
    t.string "key", null: false
    t.string "filename", null: false
    t.string "content_type"
    t.text "metadata"
    t.bigint "byte_size", null: false
    t.string "checksum", null: false
    t.datetime "created_at", null: false
    t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
  end

  create_table "campsites", force: :cascade do |t|
    t.string "url"
    t.string "name"
    t.string "parkCode"
    t.string "description"
    t.float "latitude"
    t.float "longitude"
    t.string "latLong"
    t.string "audioDescription"
    t.string "isPassportStampLocation"
    t.string "passportStampLocationDescription"
    t.string "geometryPoiId"
    t.string "reservationInfo"
    t.string "reservationUrl"
    t.string "regulationsurl"
    t.string "regulationsOverview"
    t.string "amenitiestrashRecyclingCollection"
    t.string "amenitiestoilets0"
    t.string "amenitiesinternetConnectivity"
    t.string "amenitiesshowers0"
    t.string "amenitiescellPhoneReception"
    t.string "amenitieslaundry"
    t.string "amenitiesamphitheater"
    t.string "amenitiesdumpStation"
    t.string "amenitiescampStore"
    t.string "amenitiesstaffOrVolunteerHostOnsite"
    t.string "amenitiespotableWater0"
    t.string "amenitiesiceAvailableForSale"
    t.string "amenitiesfirewoodForSale"
    t.string "amenitiesfoodStorageLockers"
    t.string "contactsemailAddresses0description"
    t.string "contactsemailAddresses0emailAddress"
    t.string "fees0cost"
    t.string "fees0description"
    t.string "fees0title"
    t.string "fees1cost"
    t.string "fees1description"
    t.string "fees1title"
    t.string "fees2cost"
    t.string "fees2description"
    t.string "fees2title"
    t.string "directionsOverview"
    t.string "directionsUrl"
    t.string "operatingHours0description"
    t.string "operatingHours0standardHourswednesday"
    t.string "operatingHours0standardHoursmonday"
    t.string "operatingHours0standardHoursthursday"
    t.string "operatingHours0standardHourssunday"
    t.string "operatingHours0standardHourstuesday"
    t.string "operatingHours0standardHoursfriday"
    t.string "operatingHours0standardHourssaturday"
    t.string "operatingHours0name"
    t.string "images0credit"
    t.string "images0title"
    t.string "images0altText"
    t.string "images0caption"
    t.string "images0url"
    t.string "images1credit"
    t.string "images1title"
    t.string "images1altText"
    t.string "images1caption"
    t.string "images1url"
    t.string "images2credit"
    t.string "images2title"
    t.string "images2altText"
    t.string "images2caption"
    t.string "images2url"
    t.string "images3credit"
    t.string "images3title"
    t.string "images3altText"
    t.string "images3caption"
    t.string "images3url"
    t.string "images4credit"
    t.string "images4title"
    t.string "images4altText"
    t.string "images4caption"
    t.string "images4url"
    t.string "images5credit"
    t.string "images5title"
    t.string "images5altText"
    t.string "images5caption"
    t.string "images5url"
    t.string "weatherOverview"
    t.string "numberOfSitesReservable"
    t.string "numberOfSitesFirstComeFirstServe"
    t.string "campsitestotalSites"
    t.string "campsitesgroup"
    t.string "campsiteshorse"
    t.string "campsitestentOnly"
    t.string "campsiteselectricalHookups"
    t.string "campsitesrvOnly"
    t.string "campsiteswalkBoatTo"
    t.string "campsitesother"
    t.string "accessibilitywheelchairAccess"
    t.string "accessibilityinternetInfo"
    t.string "accessibilitycellPhoneInfo"
    t.string "accessibilityfireStovePolicy"
    t.string "accessibilityrvAllowed"
    t.string "accessibilityrvInfo"
    t.string "accessibilityrvMaxLength"
    t.string "accessibilityadditionalInfo"
    t.string "accessibilitytrailerMaxLength"
    t.string "accessibilityadaInfo"
    t.string "accessibilitytrailerAllowed"
    t.string "accessibilityaccessRoads0"
    t.string "accessibilityclassifications0"
    t.string "lastIndexedDate"
    t.string "contactsphoneNumbers0phoneNumber"
    t.string "contactsphoneNumbers0description"
    t.string "contactsphoneNumbers0extension"
    t.string "contactsphoneNumbers0type"
    t.string "operatingHours0exceptions0exceptionHourswednesday"
    t.string "operatingHours0exceptions0exceptionHoursmonday"
    t.string "operatingHours0exceptions0exceptionHoursthursday"
    t.string "operatingHours0exceptions0exceptionHourssunday"
    t.string "operatingHours0exceptions0exceptionHourstuesday"
    t.string "operatingHours0exceptions0exceptionHoursfriday"
    t.string "operatingHours0exceptions0exceptionHourssaturday"
    t.string "operatingHours0exceptions0startDate"
    t.string "operatingHours0exceptions0name"
    t.string "operatingHours0exceptions0endDate"
    t.string "addresses0postalCode"
    t.string "addresses0city"
    t.string "addresses0stateCode"
    t.string "addresses0line1"
    t.string "addresses0type"
    t.string "addresses0line3"
    t.string "addresses0line2"
    t.string "addresses1postalCode"
    t.string "addresses1city"
    t.string "addresses1stateCode"
    t.string "addresses1line1"
    t.string "addresses1type"
    t.string "addresses1line3"
    t.string "addresses1line2"
    t.string "contactsphoneNumbers1phoneNumber"
    t.string "contactsphoneNumbers1description"
    t.string "contactsphoneNumbers1extension"
    t.string "contactsphoneNumbers1type"
    t.string "images6credit"
    t.string "images6title"
    t.string "images6altText"
    t.string "images6caption"
    t.string "images6url"
    t.string "images7credit"
    t.string "images7title"
    t.string "images7altText"
    t.string "images7caption"
    t.string "images7url"
    t.string "images8credit"
    t.string "images8title"
    t.string "images8altText"
    t.string "images8caption"
    t.string "images8url"
    t.string "images9credit"
    t.string "images9title"
    t.string "images9altText"
    t.string "images9caption"
    t.string "images9url"
    t.string "amenitiesshowers1"
    t.string "fees3cost"
    t.string "fees3description"
    t.string "fees3title"
    t.string "fees4cost"
    t.string "fees4description"
    t.string "fees4title"
    t.string "fees5cost"
    t.string "fees5description"
    t.string "fees5title"
    t.string "fees6cost"
    t.string "fees6description"
    t.string "fees6title"
    t.string "amenitiestoilets1"
    t.string "amenitiespotableWater1"
    t.string "operatingHours0exceptions1exceptionHourswednesday"
    t.string "operatingHours0exceptions1exceptionHoursmonday"
    t.string "operatingHours0exceptions1exceptionHoursthursday"
    t.string "operatingHours0exceptions1exceptionHourssunday"
    t.string "operatingHours0exceptions1exceptionHourstuesday"
    t.string "operatingHours0exceptions1exceptionHoursfriday"
    t.string "operatingHours0exceptions1exceptionHourssaturday"
    t.string "operatingHours0exceptions1startDate"
    t.string "operatingHours0exceptions1name"
    t.string "operatingHours0exceptions1endDate"
    t.string "operatingHours0exceptions2startDate"
    t.string "operatingHours0exceptions2name"
    t.string "operatingHours0exceptions2endDate"
    t.string "operatingHours0exceptions3startDate"
    t.string "operatingHours0exceptions3name"
    t.string "operatingHours0exceptions3endDate"
    t.string "operatingHours0exceptions4startDate"
    t.string "operatingHours0exceptions4name"
    t.string "operatingHours0exceptions4endDate"
    t.string "operatingHours0exceptions5startDate"
    t.string "operatingHours0exceptions5name"
    t.string "operatingHours0exceptions5endDate"
    t.string "contactsphoneNumbers2phoneNumber"
    t.string "contactsphoneNumbers2description"
    t.string "contactsphoneNumbers2extension"
    t.string "contactsphoneNumbers2type"
    t.string "passportStampImages0credit"
    t.string "passportStampImages0description"
    t.string "passportStampImages0crops0aspectRatio"
    t.string "passportStampImages0crops0url"
    t.string "passportStampImages0altText"
    t.string "passportStampImages0title"
    t.string "passportStampImages0caption"
    t.string "passportStampImages0url"
    t.string "images10credit"
    t.string "images10title"
    t.string "images10altText"
    t.string "images10caption"
    t.string "images10url"
    t.string "images11credit"
    t.string "images11title"
    t.string "images11altText"
    t.string "images11caption"
    t.string "images11url"
    t.string "images12credit"
    t.string "images12title"
    t.string "images12altText"
    t.string "images12caption"
    t.string "images12url"
    t.string "images13credit"
    t.string "images13title"
    t.string "images13altText"
    t.string "images13caption"
    t.string "images13url"
    t.string "images14credit"
    t.string "images14title"
    t.string "images14altText"
    t.string "images14caption"
    t.string "images14url"
    t.string "operatingHours0exceptions2exceptionHourswednesday"
    t.string "operatingHours0exceptions2exceptionHoursmonday"
    t.string "operatingHours0exceptions2exceptionHoursthursday"
    t.string "operatingHours0exceptions2exceptionHourssunday"
    t.string "operatingHours0exceptions2exceptionHourstuesday"
    t.string "operatingHours0exceptions2exceptionHoursfriday"
    t.string "operatingHours0exceptions2exceptionHourssaturday"
    t.string "operatingHours0exceptions3exceptionHourswednesday"
    t.string "operatingHours0exceptions3exceptionHoursmonday"
    t.string "operatingHours0exceptions3exceptionHoursthursday"
    t.string "operatingHours0exceptions3exceptionHourssunday"
    t.string "operatingHours0exceptions3exceptionHourstuesday"
    t.string "operatingHours0exceptions3exceptionHoursfriday"
    t.string "operatingHours0exceptions3exceptionHourssaturday"
    t.string "fees7cost"
    t.string "fees7description"
    t.string "fees7title"
    t.string "fees8cost"
    t.string "fees8description"
    t.string "fees8title"
    t.string "amenitiesshowers2"
    t.string "operatingHours1description"
    t.string "operatingHours1standardHourswednesday"
    t.string "operatingHours1standardHoursmonday"
    t.string "operatingHours1standardHoursthursday"
    t.string "operatingHours1standardHourssunday"
    t.string "operatingHours1standardHourstuesday"
    t.string "operatingHours1standardHoursfriday"
    t.string "operatingHours1standardHourssaturday"
    t.string "operatingHours1name"
    t.string "multimedia0title"
    t.string "multimedia0id"
    t.string "multimedia0type"
    t.string "multimedia0url"
    t.string "amenitiestoilets2"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "nps_id"
  end

  create_table "favorites", force: :cascade do |t|
    t.string "campsite_name"
    t.string "image"
    t.string "campsite_details"
    t.string "campsite_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "user_id"
    t.index ["user_id"], name: "index_favorites_on_user_id"
  end

  create_table "reviews", force: :cascade do |t|
    t.string "campsite_id"
    t.string "description"
    t.float "rating"
    t.string "site_name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "user_id"
    t.string "name"
    t.index ["user_id"], name: "index_reviews_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  add_foreign_key "active_storage_attachments", "active_storage_blobs", column: "blob_id"
  add_foreign_key "favorites", "users"
  add_foreign_key "reviews", "users"
end
